// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rovers.Dal.Concreate;

namespace Rovers.Dal.Migrations
{
    [DbContext(typeof(RoversContext))]
    [Migration("20201004110427_Rovers-v1")]
    partial class Roversv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rovers.Entity.RoversEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CREATE_DATE");

                    b.Property<DateTime?>("DELETE_DATE");

                    b.Property<bool>("IS_ACTIVE");

                    b.Property<string>("ROVER_DIRECTIVE");

                    b.Property<DateTime?>("UPDATE_DATE");

                    b.Property<string>("WAY");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("ID");

                    b.ToTable("Rovers");
                });
#pragma warning restore 612, 618
        }
    }
}
